### ISSUE TITLE
Version 2.0.0 not working on Firefox 53.0.2 (64-bit), Windows 10

### ISSUE THREAD

**Issue by dvdantunes** [autonome/alwaysright#7]
Thanks for your excellent work on this add-on, it allows such a great feature that I don't understand why Firefox doesn't have it as default.

I'm here to report that since the update to v2.0.0 the add-on is not working for me and another user (Tarabass) that left you a post at the Firefox Add-ons site (https://addons.mozilla.org/en-US/firefox/addon/always-right/). Both of us are working on Firefox 53.0.2 (64-bit), Windows 10. I don't know if that is just a coincidence or not.

For me, the issue is erratic: when I open a new tab by middle click on a link, sometimes the tab is opened at the end (far right) of the tab list, sometimes is opened just as expected, next to the current tab. This happens too when I open a new tab by CTRL+T hotkey.

Other issue that I have is that when I open a new tab by middle click, the tab list is scrolled to the beginning (far left) of the tab list, while the body of current tab is still showed. This issue doesn't happen as often as the previous issue.

Thanks! hope you can fix it. If you need another info from me, don't hesitate to ask 👍

**Comment by autonome** [comment]
Thanks for the report! I'll see if I can reproduce.

For now, you can revert back to the older version by looking at the full
version list on AMO.

**Comment by dvdantunes** [comment]
Thanks! I'll do that while you fix the issue :)

**Comment by autonome** [comment]
Hrm, I'm not able to reproduce any of the problems. I'm on a Mac, tried
installing apps to allow middle-clicks, and tried to reproduce on Firefox
for Windows on Windows 10 64 bit in a VM with VirtualBox

I did find one issue where the active tab was null before any tab switches,
so here's a 2.0.1 xpi you can try, and see if it's fixed:

https://www.dropbox.com/s/7g7ze2tj9wym4ma/always_right-2.0.1.zip?dl=0

**Comment by autonome** [comment]
Another potential cause of bugs fixed in this one:
https://www.dropbox.com/s/zxwks8clb95d0je/always_right-2.0.2.zip?dl=0

Pushing all of these fixes to AMO too.

**Comment by dvdantunes** [comment]
Thanks!, let me try it, I'll keep you posted

**Comment by danestaples** [comment]
I'm also having the same issue of tabs not always opening directly to the right with versions 2.0+ (including 2.02) on firefox 53 on linux. I can consistently reproduce the issue just by holding down ctrl + t while on a tab that has several tabs to the right and eventually one of the new tabs will open at the far right.

**Comment by dantunes** [comment]
Finished testing v2.0.2, but the bugs persist. As @danestaples said, the issue happens eventually and not all the times. Also I had plenty of tabs (about 30) to the right of the current tab when I did the tests.

On issue #8 there is a graphical explanation of the second bug that I mentioned before.

Thanks @autonome !

**Comment by Nexion** [comment]
I experienced the same issues, they happened since v2.0.0 to current version. Firefox 53, Gentoo Linux x64. Currently disabled addons auto-update and downgraded to 1.6.1.

**Comment by autonome** [comment]
I've reverted on AMO back to 1.6.1, so you can reinstall here for a working version: https://addons.mozilla.org/en-US/firefox/addon/always-right/

**Comment by autonome** [comment]
I still can't reproduce any problems *except* that restoring a closed tab puts it in the wrong place (which I can't fix until a core issue with tabs API is fixed...).

Arrgh.

**Comment by Tarabass** [comment]
I'm experiencing the same problems. Now I know how I'm used to this addon. It should be default behavior in FF..

**Comment by autonome** [comment]
@Tarabass Please re-intall the old 1.6.1 version.

I've had several conversations with Firefox design team over the many years, no interest in properly evaluating the problem. I'm thinking about submitting it as a Test Pilot Experiment, which will get a more formal evaluation of the idea.

**Comment by Tarabass** [comment]
@autonome Thx for your support. Already installed the older version, so for now I'm good.

I also noticed after installing the newest version of FF that pinned tabs are reordered after re-opening FF. I also notice that after re-installing your addon this behavior is gone. FWIW I can't say if it has something to do with your addon, but wanted to mention it.

**Comment by autonome** [comment]
Interesting, I've never seen that. Thanks for reporting it Peter! It's not
really clear when add-ons get loaded in the startup process, so I can
imagine if add-on load time is opportunistic instead deterministic and
there's still session being restored then tabs could get moved around 😢.
We saw this way back in the day and it would sometimes *reverse* the tab
order entirely! Been years since that would happen though.

**Comment by dvdantunes** [comment]
Reverted back to 1.6.1 version and everything is working as usual. @autonome thanks for your support

> I'm thinking about submitting it as a Test Pilot Experiment, which will get a more formal evaluation of the idea.

This would be a great idea, hope that it can get a green light in the future :)

**Comment by autonome** [comment]
I released new WebExtension version today. Report issues if you see them!

**Comment by Nexion** [comment]
@autonome the update seems to resolve the issues, neither of them happened so far. Thank you!

I hope you'll find a way to fix #8 too.

**Comment by autonome** [comment]
Great to hear, thanks Nexie!

Unfortunately, #8 is an issue in Firefox and the WebExtensions APIs
themselves. There's a bug for it... but I can't find it right now!

**Comment by dvdantunes** [comment]
@autonome where did you post the link for the new version .xpi file? I can't see the update on the AMO page neither find it on this repo. Thanks!

**Comment by autonome** [comment]
Weird... yeah maybe something is wrong on the site. Even the management
dashboard says it's there but then gives a 404 when I click through. Will
wait a day and see if review happens and unsticks it.

**Comment by autonome** [comment]
Ok, just go approved and is showing on main listing page now.

**Comment by Nexion** [comment]
@dvdantunes for testing purposes you can make a local copy of git repository, open **about:debugging** in Mozilla, click on "Load Temporary Add-on" and just select the extension JS file. From my experiense you can even delete the local repository copy you've made, the temporary addon will stay active in your Mozilla profile until you remove it from **about:addons**.

**Comment by Nexion** [comment]
Finally I noticed some unexpected behaviour of the recent version. After Firefox restart new tabs are always opened at the very end. The workaround is to disable and enable addon again after restarting the browser. Can someone reproduce this?

**Comment by Tarabass** [comment]
Yup, it's back. FF v55.0.1 and AR v2.0.4. To fix it I disabled and directly enabled the addon, and restarted FF. Then it works again..

I hope we don't have to do this all the time though

**Comment by autonome** [comment]
Thanks for reporting this, I'm looking into it!

**Comment by autonome** [comment]
The restart issue is fixed in #13 and pushed to AMO.

**Comment by autonome** [comment]
Fixed many moons ago, closing.
